version: '3.8'

services:
  bot:
    build: .
    restart: unless-stopped
    container_name: telegram_bot
    env_file: .env  # Используем наш .env файл
    environment:
      - DB_HOST=db  # Переопределяем хост для контейнера
      - LOG_LEVEL=DEBUG
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:12
    container_name: postgres_db
    env_file: .env  # Используем тот же .env файл
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-mydatabase}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: